### ISSUE TITLE
How to reproduce the Visual Planning experiment？

### ISSUE THREAD

**Issue by SanMumumu** [thuml/iVideoGPT#10]
Hi, thank you for sharing such excellent work!

I am a little confused about the code, how can I reproduce the vision-based model predictive control? As shown in the following table:

![image](https://github.com/user-attachments/assets/92e7330c-d082-4200-abc4-315bc22186ed)

**Comment by Manchery** [comment]
Thanks for your interest in our work. We will update this part of the code in a few days.

In general, we finetune the pretrained ivideogpt on VP2 datasets and wrap it into an interface compatible with VP2 official visual planning code.
