### ISSUE TITLE
Training time does not correspond?

### ISSUE THREAD

**Issue by xiaohao9999** [thuml/iVideoGPT#11]
Hi, 

When I reproduced the results using the standard settings（4 * RTX 3090 GPU, 16 data loader workers per device, 64 × 64 resolution）, I found that the training time does not correspond to what is reported in the paper.

![image](https://github.com/user-attachments/assets/b96e1ef1-b32b-4701-9d20-ba8399fbe358)

It takes so long to fine-tune on the biar dataset. The number of training iterations of the fine-tuned tokenizer is the same as the pre-training. Is it necessary?

**Comment by Manchery** [comment]
No, it is not necessary. You can set `--max_train_steps` as training steps reported in our paper.
