### ISSUE TITLE
action-conditioned code / checkpoint?

### ISSUE THREAD

**Issue by evelinehong** [thuml/iVideoGPT#4]
Hi,

When will you release your codes for action-conditioned training / inference codes and the checkpoint?

**Comment by Manchery** [comment]
Hi, thanks for your interest in our work!

We are currently organizing our code and will make it publicly available soon (before September).

**Comment by Manchery** [comment]
Hi, we have released our training codes for action-conditioned video prediction and visual MBRL. Note that we only conduct action-free video pre-training; thus, we do not have a checkpoint for action-conditioned prediction on OXE.

Please let me know if you have any remaining questions.

**Comment by Manchery** [comment]
Close the issue for now, but please reopen it if you have further questions. Thank you!
