### ISSUE TITLE
How do you rollout the imagination data in the MBRL experiments?

### ISSUE THREAD

**Issue by tinnerhrhe** [thuml/iVideoGPT#5]
As mentioned in Alg. 1 in Appendix A.5 of the paper, iVideoGPT performs a k-step model rollout to augment the replay buffer. In Table 5, I observed that you set the sequence length to 12 for video prediction. How do you predict 12 frames since the policy only outputs a single action for conditioning? Do you mask the remaining action tokens and only extract the predicted first frame? Could you please provide more details regarding the implementation of the model rollout?

Thank you very much! I'm looking forward to your reply.

**Comment by Manchery** [comment]
Hi, thanks for your interest in our work!

Regarding your question, we do model rollouts for MBRL by an autoregressive generation of iVideoGPT (just like the generation of LLMs). This means that we predict tokens of one frame once and then reconstruct them into predicted observations, and then the policy outputs an action based on the observation. The predicted tokens and the action are both appended into the sequence of tokens, and iVideoGPT predicts tokens of the next frame once again. This process repeats multiple times (horizon of the rollout).

We plan to release our code soon (I believe before September), and then you can refer to our implementation.

**Comment by tinnerhrhe** [comment]
Thanks for your timely response!
