### ISSUE TITLE
How to get json files?

### ISSUE THREAD

**Issue by xiaohao9999** [thuml/iVideoGPT#6]
Hi, 

Thanks for the great work! 

I downloaded the OXE data from [hugging face.](https://huggingface.co/datasets/jxu124/OpenX-Embodiment) But after running the code.

`python datasets/oxe_data_converter.py --dataset_name `

I get an error that I don't have a json file.

`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/OXE/viola/0.1.0/dataset_info.json'`

Where should I get it from?

**Comment by xiaohao9999** [comment]
Ok, that's very useful! Thanks for your prompt reply.

**Comment by xiaohao9999** [comment]
Sorry to bother you again. 

If this problem occurs during data processing, will it affect subsequent experiments?

![1733886239290](https://github.com/user-attachments/assets/aee2e0c2-8ab1-4b5c-9c1b-2303d5956309)

**Comment by xiaohao9999** [comment]
Hello. When I reinstall the environment, the above problem is solved. By the way, do I still need the downloaded source data? Or do I only need the .npz file?

**Comment by Manchery** [comment]
For our experiments, you only need extracted .npz files and can remove downloaded tensorflow data if taking too much disk space.

**Comment by xiaohao9999** [comment]
Ok! Thank u!
