### ISSUE TITLE
ConfigAttributeError: Key 'legacy_reward' is not in struct

### ISSUE THREAD

**Issue by xiaohao9999** [thuml/iVideoGPT#9]
https://github.com/thuml/iVideoGPT/blob/130bbec1d266f96da7a7195ef688f6c1990b5cc5/mbrl/train_metaworld_mbpo.py#L70-L73

This code will result in an error. Is this key still needed?

```
omegaconf.errors.ConfigAttributeError: Key 'legacy_reward' is not in struct
    full_key: legacy_reward
    object_type=dict
```

**Comment by Manchery** [comment]
This key no longer exists in our cleaned code for release. I have removed them from the latest commit. Thank you for pointing out this!

**Comment by xiaohao9999** [comment]
In fact, I still get an error after removing it. /(ㄒoㄒ)/~~

![image](https://github.com/user-attachments/assets/05bc1676-1dd7-4aa0-9494-2a48525854f4)

**Comment by Manchery** [comment]
I have tested the current code and not encountered the same issue. Did you install our specified version for metaworld?

```
pip install git+https://github.com/Farama-Foundation/Metaworld.git@83ac03ca3207c0060112bfc101393ca794ebf1bd
```

**Comment by xiaohao9999** [comment]
I reinstalled the environment, but it still didn't work. And there was no error when I installed metaworld.
The metaworld version is as follows：
`metaworld                    2.0.0`


What happens if the webpage displays "Not Found"?

![1735182854831](https://github.com/user-attachments/assets/e127492a-ebbc-4048-a8e4-23606ccb0216)

**Comment by Manchery** [comment]
You should either use this url for `pip install`, which will automatically git clone codes and setup, or visit https://github.com/Farama-Foundation/Metaworld/tree/83ac03ca3207c0060112bfc101393ca794ebf1bd to manually download the code.

**Comment by xiaohao9999** [comment]
Commenting out rgbd_tuple in the following code solves the problem. But I don't know why. Is it because the version of mujoco I installed is wrong?

/mnt/data/xxxx/Anaconda/envs/ivid/lib/python3.9/site-packages/gymnasium/envs/mujoco/mujoco_env.py
```
        assert self.metadata["render_modes"] == [
            "human",
            "rgb_array",
            "depth_array",
            # "rgbd_tuple",
        ], self.metadata["render_modes"]
```
